Update the multi-component repl &c.

diff --git a/script/ghci-flags b/script/ghci-flags
--- a/script/ghci-flags
+++ b/script/ghci-flags
@@ -3,51 +3,65 @@
 
 set -e
 
-cd $(dirname "$0")/..
+cd "$(dirname "$0")/.."
 
-root="$(pwd)"
 ghc_version="$(ghc --numeric-version)"
 
-if [ "$1" == "--builddir" ]; then
-  repl_builddir="$2"
-  shift 2
-else
-  repl_builddir=dist-newstyle
-fi
+# recent hie-bios requires us to output to the file at $HIE_BIOS_OUTPUT, but older builds & script/repl don’t set that var, so we default it to stdout
+output_file="${HIE_BIOS_OUTPUT:-/dev/stdout}"
 
-echo "-O0"
-echo "-ignore-dot-ghci"
+build_dir="dist-newstyle/build/x86_64-osx/ghc-$ghc_version"
+build_products_dir="$build_dir/build-repl"
 
-echo "-outputdir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build"
-echo "-odir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build"
-echo "-hidir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build"
-echo "-stubdir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build"
+cores=$(sysctl -n machdep.cpu.core_count || echo 4)
 
-echo "-i$root/src"
-echo "-i$root/test"
+function flags {
+  # disable optimizations for faster loading
+  echo "-O0"
+  # don’t load .ghci files (for ghcide)
+  echo "-ignore-dot-ghci"
 
-echo "-optP-include"
-echo "-optP$root/$repl_builddir/build/x86_64-osx/ghc-$ghc_version/build/autogen/cabal_macros.h"
+  # use as many jobs as there are physical cores
+  echo "-j$((cores + 1))"
 
-echo "-hide-all-packages"
+  # where to put build products
+  echo "-outputdir $build_products_dir"
+  echo "-odir $build_products_dir"
+  echo "-hidir $build_products_dir"
+  echo "-stubdir $build_products_dir"
 
-# Emit package flags from the environment file, removing comments & prefixing with -
-cabal exec --builddir="$repl_builddir" -v0 bash -- -c 'cat $GHC_ENVIRONMENT' | grep -v '^--' | sed -e 's/^/-/'
+  # .hs source dirs
+  echo "-isrc"
+  echo "-ibenchmark"
+  echo "-iexamples"
+  echo "-itest"
 
-echo "-XHaskell2010"
+  # disable automatic selection of packages
+  echo "-hide-all-packages"
 
-echo "-Wwarn"
+  # run cabal and emit package flags from the environment file, removing comments & prefixing with -
+  cabal v2-exec -v0 bash -- -c 'cat "$GHC_ENVIRONMENT"' | grep -v '^--' | sed -e 's/^/-/'
 
-echo "-Weverything"
-echo "-Wno-all-missed-specialisations"
-echo "-Wno-implicit-prelude"
-echo "-Wno-missed-specialisations"
-echo "-Wno-missing-import-lists"
-echo "-Wno-missing-local-signatures"
-echo "-Wno-monomorphism-restriction"
-echo "-Wno-name-shadowing"
-echo "-Wno-safe"
-echo "-Wno-unsafe"
+  # default language extensions
+  echo "-XHaskell2010"
 
-[[ "$ghc_version" = 8.6.* ]] && echo "-Wno-star-is-type" || true
-[[ "$ghc_version" = 8.8.* ]] && echo "-Wno-missing-deriving-strategies" || true
+  # treat warnings as warnings
+  echo "-Wwarn"
+
+  # default warning flags
+  echo "-Weverything"
+  echo "-Wno-all-missed-specialisations"
+  echo "-Wno-implicit-prelude"
+  echo "-Wno-missed-specialisations"
+  echo "-Wno-missing-import-lists"
+  echo "-Wno-missing-local-signatures"
+  echo "-Wno-monomorphism-restriction"
+  echo "-Wno-name-shadowing"
+  echo "-Wno-safe"
+  echo "-Wno-unsafe"
+  [[ "$ghc_version" = 8.6.* ]] || [[ "$ghc_version" = 8.8.* ]] || [[ "$ghc_version" = 8.10.* ]] && echo "-Wno-star-is-type" || true
+  [[ "$ghc_version" = 8.8.* ]] || [[ "$ghc_version" = 8.10.* ]] && echo "-Wno-missing-deriving-strategies" || true
+  [[ "$ghc_version" = 8.10.* ]] && echo "-Wno-missing-safe-haskell-mode" && echo "-Wno-prepositive-qualified-module" && echo "-Wno-unused-packages"
+}
+
+flags > "$output_file"
